### ISSUE TITLE
wrong item selected when filtered once

### ISSUE THREAD

**Issue by iwin4aids** [istvan-ujjmeszaros/bootstrap-duallistbox#110]
Hi~I have met some problem in the duallistbox's filter use case :(version 3.0.6)
When I filtered with some word, whatever item I clicked will not jump to the right side but always the top element is selected and jump to the right side, all behavior going to be OK after your first item click, but just at the first time you click ,the top item will be "selected" into the right side.
You could test it in the demo showcase, I use the latest chrome browser btw.
I report this to hope you can fix it!
Thank you!

**Comment by dominik-bln** [comment]
I can confirm this issue. Steps to reproduce on the example Page http://www.virtuosoft.eu/code/bootstrap-duallistbox/ :

- Type "Op" in the left box
- Click on "Option 2"

This moves "Option 1" to the right side instead of "Option 2".

**Comment by attitudemattrs** [comment]
I ran into this same issue yesterday using 3.0.5.  I have reproduced the problem in both the example page (entering filter "1" and trying to pick Option 10 - Option 1 moves) and in my own example.  Note that I have only been able to reproduce the issue in chrome (currently using 55.0.2883.87).  I have not been able to reproduce the issue using IE 10+ or Firefox.

**Comment by shpontex** [comment]
i found that if you try to select after filtring and you click anywhere before you select something it will work , because the focus in the input filter will be lost,
so the best thing to do is write a code that will lost focus on input after the search

this is workerd for me 

$(document).on('mouseover',"select",function(){
	$(this).parent().find(".filter").blur();
});

when you hover the select the focus on the input related with the select will be lost , so now you can choose the option that you want

hope will help

**Comment by attitudemattrs** [comment]
Appreciate the post shpontex.  I can confirm that your suggestion corrected our problem.   Thanks!

**Comment by RickHutten** [comment]
Based on the answer of @shpontex I adjusted it a little bit so you don't have the side-effect of losing focus if you hover over the select element: 

$(document).on('keyup', ".bootstrap-duallistbox-container .filter", function () {
        $(this).blur();
        $(this).focus();
    });

This disables the focus and than resets it after every key press which seems to work on my computer

**Comment by MareoRaft** [comment]
This may be a Chrome glitch because Chrome selects the first option in the list even when you click on any other option.  Has an issue been opened for this there?

**Comment by ceds** [comment]
Having same issues.  Fixed it with proposal from RickHutten

**Comment by KuKan1** [comment]
Having same issues .RickHutten's answer is useful,but it's very difficult when coding chinese

**Comment by MareoRaft** [comment]
Here is a more pure JS version of @RickHutten 's solution.  It actually uses lodash.  Please post a better version here if you have one.

    function isProbablyDuallistboxFilter(class_list) {
      return class_list.length === 3 &&
        _.includes(class_list, 'filter') &&
        _.includes(class_list, 'form-control') &&
        _.includes(class_list, 'ng-scope')
    }
    document.addEventListener('keyup', function (event) {
      // determine if the target is a duallistbox filter
      if (isProbablyDuallistboxFilter(event.target.classList)) {
        var nonselectedListboxElement = document.getElementById('bootstrap-duallistbox-nonselected-list_');
        nonselectedListboxElement.focus();
        // var thisElement = document.querySelector('.bootstrap-duallistbox-container .filter');
        // thisElement.focus();
        event.target.focus();
      }
    });

**Comment by helenatxu** [comment]
I had a different issue using duallistbox in Rails, when I used the filter to find and select an item, rails would send weird nested parameters (saying also 'unpermitted parameters' that were correctly permitted in the controller) and wouldn't save my data.

@RickHutten fix solved it for me. Thanks
