### ISSUE TITLE
Add bootstrap 4 support

### ISSUE THREAD

**Issue by subprime** [istvan-ujjmeszaros/bootstrap-duallistbox#116]
**For the next generation of bootstrap it is important to adapt few things.**
List of known issues:

1. glyphicon is not supported by default => It's possible to define icons over the configuration? (For example using awesome fonts)

**Comment by mybigman** [comment]
+1

**Comment by tpetry** [comment]
Bootstrap 4 Beta has been released a few weeks ago. As stated by the devs there will most likely be no more breaking changes.

**Comment by diogenesdirkx** [comment]
I tried to use Bootstrap-duallistbox with the new  Bootstrap 4-beta and 2 things break

First: 
They dropped Glyphicon i use font-awesome instead. 

adaQuest has a pull request to adding a option to change the icon library.

Second: 
They dropped the btn-default class, i made one for me but the default css don't have it.
A option to change the class on the buttons is need.

**Comment by marccollin** [comment]
any update for bootstrap 4 support

**Comment by istvan-ujjmeszaros** [comment]
You can expect it in the coming days.

**Comment by marcelozarate** [comment]
I have a version that supports Bootstrap 4. Shall I PR?

**Comment by istvan-ujjmeszaros** [comment]
Thanks @marcelozarate, looking.

**Comment by istvan-ujjmeszaros** [comment]
I have published a new version updated to Bootstrap 4. Decided to remove Bootstrap 2 & 3 support from it, but created a new branch (`v4`) and made it the default branch. The verson number will be `v4.x.x`. The Bootstrap 2 & 3 version will remain in the (now obsolete) `main` branch, with `v3.x.x` as the version number.
The package name is updated as well (`bootstrap4-duallistbox`) as I couldn't publish to `bootstrap-duallistbox` package.

Please open a new ticket for any Bootstrap 4 related issue.
