### ISSUE TITLE
How do I preserve selected order in right hand list? (and apology)

### ISSUE THREAD

**Issue by chrisloughnane** [istvan-ujjmeszaros/bootstrap-duallistbox#135]
I'm sorry to post this here but I have spent the last five hours reading all the posts here and searched online. I've tried a number of options but none intuitively jump out as preserving selection order.

e.g.
if I have elements 1,2,3,4 and I select in this order 4,3,2 I want the right hand list in the order 4,3,2. Right now the list is sorted automatically to 2,3,4.

Could you please tell me what parameter am I missing?

Thank you for the great library.

**Comment by chrisloughnane** [comment]
I closed this ticket too soon. By setting the option:

`sortByInputOrder: 'true'`

The RHS box maintains the order of selection but when I collect the values with

`$('select[name="buildcontent[]"]').val()`

it sorts them again.

How can I get the values in the order I have select them?

**Comment by chrisloughnane** [comment]
@istvan-ujjmeszaros unfortuantely that just controls when an item moves. When you click on it or use the button.

**Comment by chrisloughnane** [comment]
@jsanchezsol1991   Thanks for your suggestion
I tried your suggestion and my inner function is not picking up any values from the selected list.

I initalise my duallist with:
```
     var build = $('#buildcontent').bootstrapDualListbox({
            nonSelectedListLabel: 'Non-selected',
            selectedListLabel: 'Selected for your <c:out value="${typeDisplay}"></c:out>',
            sortByInputOrder: 'true'
        });
//and I test with
        $('#test').click(function(){
            var campos= [];
            $('#bootstrap-duallistbox-selected-list_buildcontent').each(function (){
                campos.push($(this).val());
            });
            alert(campos);
        });
```

Do you see anything wrong with that?

**Comment by jsanchezsol1991** [comment]
yep! you forgot to put option .... so try it : 

$('#test').click(function(){
            var campos= [];
            $('#bootstrap-duallistbox-selected-list_buildcontent option').each(function (){
                campos.push($(this).val());
            });
            alert(campos);
        });

**Comment by chrisloughnane** [comment]
Thanks for that, I had added the option in my test code, I copy pasted and older version to here. 
But it still isn't working. It behaves like a dynamically added element.

`$('#buildcontent').html()`

will return the element's contents but

`$('#bootstrap-duallistbox-selected-list_buildcontent option').html()`

returns 'is undefined'

So far the only command that returns selected values is:

`$('#buildcontent').val()`

The generated select box
```
<select multiple="multiple" id="bootstrap-duallistbox-selected-list_buildcontent[]" class="form-control" name="buildcontent[]_helper2" style="height: 172px;">
	<option value="12" data-sortindex="0">test 1</option>
	<option value="10" data-sortindex="1">test 2</option>
	<option value="6" data-sortindex="2">test 3</option>
</select>
```

I am at a loss with this. I even tried to unpick the library but there are far too many single letter variables to make sense of.

**Comment by chrisloughnane** [comment]
@jsanchezsol1991 
I rewrote my code from scratch and with your help it now works. Thank you very much for your help :)

**Comment by m0hamedessam** [comment]
@chrisloughnane how you fix it can you share it i need to sort it out too please

**Comment by Bruskyer** [comment]
// delete selected 
  $("#btnDelete").click(function (e) {
    var deloption = $('select[name="leftList_helper2"] option:selected');
    $(deloption).remove();
    e.preventDefault();
   $('select[name="leftList_helper2"]').bootstrapDualListbox("refresh", true);
  });
I move option from left  to rightbox and when I delete option from right box  both boxes appear empty but at last when click any move btn  it shows all deleted option again.
pls any suggestion or help?
Thanks
