### ISSUE TITLE
missing method to move elements between lists

### ISSUE THREAD

**Issue by mirandacarlos** [istvan-ujjmeszaros/bootstrap-duallistbox#139]
I'm trying to do a custom "move all" to exclude some values when user click the button. Any ideas how this could be done? i was expecting a method "move" for example

**Comment by mirandacarlos** [comment]
Solved it by setting the prop selected of the options and triggering the change event of the select

**Comment by dshastry** [comment]
Are you doing this on the original selectbox or on the unselected values select drawn by listbox?

**Comment by mirandacarlos** [comment]
on the unselected values list. this is the code i used (i wanted to move all except the Portugal ones):
on the document.ready function added:
$('.moveall').unbind().click(function(){
        $('select[id*=bootstrap-duallistbox-nonselected] > option:not(:contains(Portugal))').prop('selected', true);
        $('select[id*=bootstrap-duallistbox-nonselected]').trigger('change');
    });
