### ISSUE TITLE
Selected list items disappear when option id is given

### ISSUE THREAD

**Issue by ceds** [istvan-ujjmeszaros/bootstrap-duallistbox#165]
I have a very strange problem.  I have a SELECT with about 1500 OPTION items.  

When giving each OPTION a 'value' of between 500 - 5000 depending on the record id, the selected list items disappear when selecting items.  I have to double click on the selected items box for them to appear again.

This is very strange as it does not happen when the OPTION value is not set.

Any ideas ?

No strange or weird code is used.  Everything as per demo on github.

I'm using V4.0.1

**UPDATE**

It seems that giving the Id is not the root cause of the problem.  What happens is I update the GUI on a different tab (that only worked when Id was given), and for some reason the SELECT control loses focus or something.  I managed to get it working by running the 'refresh' method after GUI is updated.  However, it's VERY slow and creates a bad user experience.

Any other tricks that I might try ?

**Comment by istvan-ujjmeszaros** [comment]
Please update to v4.0.2, it should fix this issue. Feel free to re-open if it doesn't help.
This is the related issue: #160
