### ISSUE TITLE
Is there any way for me to rename the rightside box name?

### ISSUE THREAD

**Issue by WeiLinJoe** [istvan-ujjmeszaros/bootstrap-duallistbox#206]
the rightside box name is  xxxx_helper2  now ,  i wanna change it for submit 😂

**Comment by istvan-ujjmeszaros** [comment]
The submitted data will be available in your original select (`<select multiple="multiple" name="xxxx[]">`), on which you can freely decide about the name. You shouldn't work with the helper selects that were generated by the plugin.
If you need support then please use StackOverflow.
