### ISSUE TITLE
Ajax Search

### ISSUE THREAD

**Issue by wandersonwhcr** [istvan-ujjmeszaros/bootstrap-duallistbox#46]
OMG! I loved this plugin! I created one like this, but it belongs to my old job :(

How can I do an Ajax search when filtering?

**Comment by tnlthanzeel** [comment]
> You can trigger this event, but there is no need to use it since v3.0.0, the new version supports calling the methods with this formula: `$(selector).bootstrapDualListbox(methodName, parameter);`, please see the documentation for some examples.

we checked the document but found no examples. can u link examples here for ajax search please
