### ISSUE TITLE
Unable to move single searched item on auto move

### ISSUE THREAD

**Issue by AvadheshChoudhary** [istvan-ujjmeszaros/bootstrap-duallistbox#90]
When we search for any item and it shows only one result item, its unable to move sometimes with auto move option. Issue exists on demo site also.
<img width="1440" alt="screen shot 2016-04-19 at 1 28 58 pm" src="https://cloud.githubusercontent.com/assets/17192362/14631412/e272f136-0630-11e6-96cf-7e63f8873133.png">

**Comment by marcelozarate** [comment]
I can't reproduce the issue, can you write down the steps you took?

**Comment by AvadheshChoudhary** [comment]
Hi, 
Here are the steps...

1. I search for '1', it shows me two options [Option 1,Option 10].( Attached screenshot )
2.  then I clicked on 'Option 10', it moves to selected drop down.
3.  Secnarion 1 - Unable to move 'Option 1'  to selected dropdowm.
4. Scenarion  2-Unable to move  'Option 10' to unselected dropdown.

It behaves inconsistent.

**Comment by marcelozarate** [comment]
Still works fine for me, using both Firefox and Chrome in GNU/Linux.

Do you get any error messages in the console? Can you test it in another browser? Just trying to narrow down the bug.

**Comment by marcelozarate** [comment]
Please answer in #66
