### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by tsneed290** [istvan-ujjmeszaros/bootstrap-duallistbox#95]
Could we get NPM support for this? I don't see it published in the NPM Registry.

Thanks!
Tim

**Comment by rafaferry** [comment]
+1

**Comment by marcelozarate** [comment]
[Link](https://www.npmjs.com/package/bootstrap4-duallistbox)

**Comment by tsneed290** [comment]
@marcelozarate we have a legacy project that is still using v3.0.2. Is there any chance you could publish that version?
